# .goreleaser.yml
version: 2

before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -X github.com/scottyeager/pal/cmd.version={{.Version}}
    binary: pal

archives:
  - formats:
      - binary
    name_template: "pal-{{.Os}}-{{.Arch}}"

release:
  github:
    owner: scottyeager
    name: pal
  draft: false
  prerelease: auto
