name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Build binaries
        run: |
          GOOS=linux GOARCH=amd64 go build -ldflags "-X github.com/scottyeager/pal/cmd.version=${github.ref_name}" -o pal-linux-amd64
          GOOS=linux GOARCH=arm64 go build -ldflags "-X github.com/scottyeager/pal/cmd.version=${github.ref_name}" -o pal-linux-arm64
          GOOS=darwin GOARCH=amd64 go build -ldflags "-X github.com/scottyeager/pal/cmd.version=${github.ref_name}" -o pal-darwin-amd64
          GOOS=darwin GOARCH=arm64 go build -ldflags "-X github.com/scottyeager/pal/cmd.version=${github.ref_name}" -o pal-darwin-arm64

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            pal-linux-amd64
            pal-linux-arm64
            pal-darwin-amd64
            pal-darwin-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
